### ISSUE TITLE
Map problems

### ISSUE THREAD

**Issue by s18982** [pjwstkIOprojekt/webclient#54] opened 2022-06-01 21:03 UTC
For sure, we have big map problem.  The search of place is buggy. Most streets outside of Warsow are impossible to find. The issue also applies to big cities (except Warsow). The search engine seems to find the closest locations to Warsaw. But the problem is deeper. For example I cannot find any street from Lublin, even when the search engine doesn't find any other places.

**Comment by s20967** [comment] 2022-06-02 10:51
This issue was caused by the fact that search results outside of Warsaw were filtered in order to showcase the new functionality during previous classes. The issue is fixed now, the map will now search all places that are currently visible on the map (those were the requirements that we received).

**Closed by s20967** 2022-06-02 10:51 UTC
